//-----------------------------------------------------------
// This is a generated class. Avoid customizing code here !
// Generated by DAO Generator - version : 1.0.3
// Date : 7 Jul 2006 - Time 08:26:15
//-----------------------------------------------------------
// This class was generated by the standard template
// Template name    : vo.vm
// Template author  : Laurent GUERIN 
// Template version : 1.01
//-----------------------------------------------------------


package reflect.lib.td1 ;

import java.io.Serializable;


public class Book  implements Serializable
{
	private static final long serialVersionUID = 1L;
	
	//----------------------------------------------------------------------
    // ATTRIBUTES 
    //----------------------------------------------------------------------
    private String     _sTitle = "";     
    private double     _dPrice = 0.0;     
    private int        _iAvailability = 0;     
    private int        _iAuthorId    = 0;  // KEY ELEMENT     
    private String     _sCode  = "";  // KEY ELEMENT     

    //----------------------------------------------------------------------
    // GETTERS & SETTERS
    //----------------------------------------------------------------------

    //--- FIELD : book_title ( varchar )
    public void setTitle( String value )
    {
        this._sTitle = value;
    }
    public String getTitle()
    {
        return this._sTitle;
    }

    //--- FIELD : book_price ( decimal )
    public void setPrice( double value )
    {
        this._dPrice = value;
    }
    public double getPrice()
    {
        return this._dPrice;
    }

    //--- FIELD : book_availability ( tinyint )
    public void setAvailability( int value )
    {
        this._iAvailability = value;
    }
    public int getAvailability()
    {
        return this._iAvailability;
    }

    //--- KEY : auth_id ( int )
    public void setAuthorId( int value )
    {
        this._iAuthorId = value;
    }
    public int getAuthorId()
    {
        return this._iAuthorId;
    }

    //--- KEY : book_code ( char )
    public void setCode( String value )
    {
        this._sCode = value;
    }
    public String getCode()
    {
        return this._sCode;
    }
  
    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
        return _sTitle + "|" + _dPrice + "|" + _iAvailability + "|" + _iAuthorId + "|" + _sCode ;
    }
}

